name: Docker Image CI

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch
  pull_request: # Triggers the workflow on pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: app-test:${{ github.sha }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        file: Dockerfile
        tags: ${{ env.DOCKER_IMAGE }}

    - name: Install dev dependencies
      run: |
        docker run --rm \
            ${{ env.DOCKER_IMAGE }} \
            pip install coverage

    - name: Run tests with coverage
      run: |
        docker run --rm \
            -v ${{ github.workspace }}:/home/appuser \
            ${{ env.DOCKER_IMAGE }} \
            /bin/bash -c "python -m coverage run manage.py test && python -m coverage report"
