name: Docker Image CI

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch
  pull_request: # Triggers the workflow on pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up base environment
      run: |
        # Update package lists
        apt-get update && apt-get install -y wget lsb-release gnupg
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
        echo "deb https://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
        
        # Install PostgreSQL client and gettext
        apt-get update && apt-get install -y postgresql-client-14 gettext
        
    - name: Install Python dependencies
      run: |
        # Install and configure pipenv
        pip install pipenv

        # Install project dependencies
        pipenv install --dev --deploy --system

    - name: Run tests with coverage
      run: |
        coverage run manage.py test
        python -m coverage report
